#!/usr/bin/env bash
# t-extras.sh — the curated catalogue system (W-extras).
#
#   X1  catalogue.tsv parses: 17 columns on every data row, unique ids, the closed
#       verdict enum (RECOMMEND|MAYBE|SKIP), the closed kind enum (skill|mcp|workflow),
#       a review stamp on every row, and the impeccable row exactly as decided (F6).
#   X2  `gob extras list`: exit 0, the group headers, the row count matches the file;
#       `list <category>` filters; an unknown category is bad input (exit 2), not an
#       empty table.
#   X3  `gob extras show <id>`: every field label, values matching the file; an unknown
#       id is bad input (exit 2).
#   X4  THE ALLOWLIST RULE: `install <unknown-id>` refuses (exit 2) and writes NOTHING;
#       a SKIP-verdict row refuses (exit 1); a MAYBE row installs on an explicit
#       command (the verdict decides defaults at init, not installability).
#   X5  install flows: skill -> .gob/extras/<name>/ (standalone), skill -> the
#       platform's project skills root (read from adapters/<id>/adapter.tsv, the
#       sync_platforms pattern) with --platform, mcp -> the printed mcp.json snippet
#       and --with-mcp-config's ask-once merge (generated bytes again = no-op, a
#       customized entry = refusal), idempotent re-install (unchanged), and a modified
#       local copy is never clobbered.
#   X6  init: the bare brief carries the catalogue_suggestions AND discover_extras
#       sections (the schema keys, the inert rule); the --heuristic fallback suggests
#       from the matches column (a react repo pre-ticks RECOMMEND rows only, a MAYBE
#       row unticked, a SKIP row never); --write honours TICKED rows only (unticked
#       MAYBE installs nothing) and an unknown ticked id fails the whole --write.
#   X7  the docs: README carries the extras section (the allowlist, the offline
#       payload, suggestions-never-install, the discover tier, the curation surface)
#       and the GUIDE teaches the command where a reader decides.
#
# Everything runs in a mktemp repo under a throwaway HOME, like t-init.sh does; the
# catalogue and payload are the shipped ones (the same files the CLI reads by default).
set -uo pipefail

SRC=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
WORK=$(mktemp -d)
HOMEDIR="$WORK/home"; mkdir -p "$HOMEDIR"
CAT="$SRC/extras-catalogue/catalogue.tsv"
EXTRAS="$SRC/bin/goblin-extras"
fail=0
note() { printf '      %s\n' "$*"; }
check() { if [ "$2" -eq 0 ]; then note "ok   $1"; else note "FAIL $1"; fail=1; fi; }
# run the CLI the way a user does (through the dispatcher where the verb matters)
gx() { HOME="$HOMEDIR" bash "$SRC/bin/goblin" extras "$@"; }
gxb() { HOME="$HOMEDIR" bash "$EXTRAS" "$@"; }

# ---- X1: the catalogue parses --------------------------------------------------
[ -f "$CAT" ]; check "X1 catalogue.tsv exists at extras-catalogue/" "$?"
HDR=$(head -n 1 "$CAT")
[ "$(printf '%s' "$HDR" | awk -F'\t' '{print NF}')" -eq 17 ]
check "X1 the header carries the 17 recommended columns" "$?"
for col in id category kind name source_repo path_within_repo has_skill_md license stars \
           last_push matches conflicts requires install_hint verdict reviewed_by reviewed_date; do
  printf '%s' "$HDR" | grep -qF "$col" || break
done
[ "$(printf '%s' "$HDR" | awk -F'\t' '{print NF}')" -eq 17 ] && \
  printf '%s' "$HDR" | tr '\t' '\n' | sort > /tmp/x1.hdrs
printf '%s\n' id category kind name source_repo path_within_repo has_skill_md license \
  stars last_push matches conflicts requires install_hint verdict reviewed_by reviewed_date \
  | sort > /tmp/x1.want
cmp -s /tmp/x1.hdrs /tmp/x1.want
check "X1 every column name is exact (order-insensitive)" "$?"
BADNF=$(awk -F'\t' 'NR>1 && NF!=17 {print $1}' "$CAT")
[ -z "$BADNF" ]; check "X1 every data row carries 17 fields" "$?"
DUP=$(awk -F'\t' 'NR>1 {c[$1]++} END {for (k in c) if (c[k]>1) print k}' "$CAT")
[ -z "$DUP" ]; check "X1 ids are unique" "$?"
BADV=$(awk -F'\t' 'NR>1 && $15 !~ /^(RECOMMEND|MAYBE|SKIP)$/ {print $1}' "$CAT")
[ -z "$BADV" ]; check "X1 verdict is the closed enum (RECOMMEND|MAYBE|SKIP)" "$?"
BADK=$(awk -F'\t' 'NR>1 && $3 !~ /^(skill|mcp|workflow)$/ {print $1}' "$CAT")
[ -z "$BADK" ]; check "X1 kind is the closed enum (skill|mcp|workflow)" "$?"
NOSTAMP=$(awk -F'\t' 'NR>1 && ($16=="" || $17 !~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/) {print $1}' "$CAT")
[ -z "$NOSTAMP" ]; check "X1 every row carries reviewed_by + reviewed_date" "$?"
awk -F'\t' '$1=="impeccable" && $5=="pbakaus/impeccable" && $8=="Apache-2.0" && \
            $9=="78552" && $10=="2026-10-07" && $11 ~ /frontend/ && $15=="RECOMMEND"' "$CAT" \
  | grep -q impeccable
check "X1 the impeccable row is F6's decision (RECOMMEND, Apache-2.0, frontend, 78552)" "$?"
[ "$(awk -F'\t' 'NR>1' "$CAT" | wc -l)" -gt 30 ]
check "X1 the catalogue carries the researched superset (41 rows incl. MAYBE/SKIP)" "$?"

# ---- X2: list ------------------------------------------------------------------
OUT=$(gx list 2>&1); RC=$?
check "X2 list exits 0" "$RC"
printf '%s' "$OUT" | grep -qF '[frontend]'; check "X2 list groups by category ([frontend])" "$?"
printf '%s' "$OUT" | grep -qF '[testing]'; check "X2 list groups by category ([testing])" "$?"
ROWS=$(printf '%s' "$OUT" | grep -cE '^  [a-z0-9-]+ +[a-z]+ +[0-9]+ ')
FILE_ROWS=$(awk -F'\t' 'NR>1' "$CAT" | wc -l)
[ "$ROWS" -eq "$FILE_ROWS" ]
check "X2 list prints every catalogue row ($ROWS of $FILE_ROWS)" "$?"
OUTF=$(gx list testing 2>&1)
printf '%s' "$OUTF" | grep -qF 'playwright-mcp' && ! printf '%s' "$OUTF" | grep -qF 'taste-skill'
check "X2 list <category> filters to that category" "$?"
gx list nosuchcat >/dev/null 2>&1; check "X2 an unknown category is bad input (exit 2)" "$([ $? -eq 2 ] && echo 0 || echo 1)"

# ---- X3: show ------------------------------------------------------------------
OUT=$(gx show impeccable 2>&1); RC=$?
check "X3 show exits 0" "$RC"
for label in "id:" "category:" "kind:" "source_repo:" "license:" "stars:" "verdict:"; do
  printf '%s' "$OUT" | grep -qF "$label" || { RC=1; break; }
done
check "X3 show prints every field label" "$RC"
printf '%s' "$OUT" | grep -qF 'pbakaus/impeccable'
check "X3 show prints the row's values (source_repo)" "$?"
gx show not-an-id >/dev/null 2>&1
check "X3 an unknown id is bad input (exit 2)" "$([ $? -eq 2 ] && echo 0 || echo 1)"

# ---- X4: the allowlist ---------------------------------------------------------
P="$WORK/repo"; mkdir -p "$P"; cd "$P" || exit 1
git init -q -b main
BEFORE=$(find . -not -path './.git/*' | sort)
gxb install totally-unknown-id --target . >/dev/null 2>&1
RC=$?
AFTER=$(find . -not -path './.git/*' | sort)
check "X4 install of an unknown id refuses (exit 2)" "$([ "$RC" -eq 2 ] && echo 0 || echo 1)"
[ "$BEFORE" = "$AFTER" ]; check "X4 the refused install wrote NOTHING (the allowlist holds)" "$?"
SKIPID=$(awk -F'\t' 'NR>1 && $15=="SKIP" {print $1; exit}' "$CAT")
gxb install "$SKIPID" --target . >/dev/null 2>&1
check "X4 a SKIP-verdict row refuses install (exit 1, verdict is the contract)" "$([ $? -eq 1 ] && echo 0 || echo 1)"
MAYBEID=$(awk -F'\t' 'NR>1 && $15=="MAYBE" && $3=="skill" {print $1; exit}' "$CAT")
MAYBEPAYLOAD="$SRC/extras-catalogue/payload/$MAYBEID"
if [ -d "$MAYBEPAYLOAD" ]; then
  gxb install "$MAYBEID" --target . >/dev/null 2>&1
  check "X4 a MAYBE row installs on an explicit command (visible, never a default)" "$?"
else
  gxb install "$MAYBEID" --target . >/dev/null 2>&1
  RC=$?
  [ "$RC" -eq 2 ] && printf '%s' "$RC" | grep -qF 2
  # refusal reason is the missing payload (exit 2), never the verdict
  check "X4 a MAYBE row is installable in principle (payload-missing, not verdict refusal)" "$([ "$RC" -eq 2 ] && echo 0 || echo 1)"
fi

# ---- X5: the install flows -----------------------------------------------------
# the shipped vendored payload row (the placeholder layout the curator replaces)
SKID=taste-skill
OUT=$(gxb install "$SKID" --target . 2>&1); RC=$?
check "X5 a skill installs standalone (exit 0)" "$RC"
[ -f ".gob/extras/taste/SKILL.md" ]; check "X5 standalone skill lands in .gob/extras/<name>/SKILL.md" "$?"
OUT=$(gxb install "$SKID" --target . 2>&1)
printf '%s' "$OUT" | grep -qF 'unchanged'
check "X5 a second install is a no-op (unchanged, idempotent)" "$?"
OUT=$(gxb install "$SKID" --target . --platform claude 2>&1); RC=$?
check "X5 --platform claude installs (exit 0)" "$RC"
[ -f ".claude/skills/taste/SKILL.md" ]
check "X5 the platform copy follows adapters/<id>/adapter.tsv's skills_path_project" "$?"
PROJ_ROOT=$(awk -F'\t' '!/^#/ && NF>1 && $1!="id" {print $4}' "$SRC/adapters/hermes/adapter.tsv")
PROJ_ROOT="${PROJ_ROOT%%<name>*}"; PROJ_ROOT="${PROJ_ROOT%/}"
[ -f "./$PROJ_ROOT/taste/SKILL.md" ] || { gxb install "$SKID" --target . --platform hermes >/dev/null 2>&1; }
[ -f "./$PROJ_ROOT/taste/SKILL.md" ]
check "X5 --platform hermes lands under the adapter's own root (.$PROJ_ROOT)" "$?"
gxb install "$SKID" --target . --platform nosuchadapter >/dev/null 2>&1
check "X5 an unknown --platform is bad input (exit 2)" "$([ $? -eq 2 ] && echo 0 || echo 1)"
OUT=$(gxb install "$SKID" --target . --dry-run 2>&1)
printf '%s' "$OUT" | grep -qF 'plan:' && ! printf '%s' "$OUT" | grep -qF 'wrote '
check "X5 --dry-run plans and writes nothing" "$?"
# the never-clobber rule
printf 'local edit\n' >> ".gob/extras/taste/SKILL.md"
gxb install "$SKID" --target . >/dev/null 2>&1
RC=$?
grep -qF 'local edit' ".gob/extras/taste/SKILL.md"
check "X5 a modified local copy is never clobbered (refusal, exit 1)" "$([ "$RC" -eq 1 ] && echo 0 || echo 1)"
# the mcp flows
MCPTICK=$(awk -F'\t' 'NR>1 && $3=="mcp" && $14 ~ /^npx / {print $1; exit}' "$CAT")
MCPHINT=$(awk -F'\t' -v id="$MCPTICK" 'NR>1 && $1==id {print $14}' "$CAT")
OUT=$(gxb install "$MCPTICK" --target . 2>&1); RC=$?
check "X5 an mcp row prints its snippet and exits 0 (no registration without the flag)" "$RC"
printf '%s' "$OUT" | grep -qF '"mcpServers"'
check "X5 the snippet is the mcp.json shape" "$?"
[ ! -f .mcp.json ]; check "X5 the bare mcp install writes no .mcp.json" "$?"
gxb install "$MCPTICK" --target . --with-mcp-config >/dev/null 2>&1
RC=$?
[ -f .mcp.json ] && grep -qF "$MCPTICK" .mcp.json
check "X5 --with-mcp-config merges the row into .mcp.json" "$RC"
OUT=$(gxb install "$MCPTICK" --target . --with-mcp-config 2>&1)
printf '%s' "$OUT" | grep -qF 'unchanged'
check "X5 the same merge again is a named no-op (ask-once)" "$?"
printf '{"mcpServers":{"%s":{"command":"custom","args":[]}}}' "$MCPTICK" > .mcp.json
gxb install "$MCPTICK" --target . --with-mcp-config >/dev/null 2>&1
RC=$?
grep -qF '"custom"' .mcp.json
check "X5 a customized entry is never overwritten (refusal, ask-once)" "$([ "$RC" -eq 1 ] && echo 0 || echo 1)"
# the workflow flow is the payload contract (no workflow payload is shipped yet: refusal names the fix)
WFID=$(awk -F'\t' 'NR>1 && $3=="workflow" && $15!="SKIP" {print $1; exit}' "$CAT")
if [ -n "$WFID" ] && [ ! -d "$SRC/extras-catalogue/payload/$WFID" ]; then
  OUT=$(gxb install "$WFID" --target . 2>&1); RC=$?
  printf '%s' "$OUT" | grep -qF 'no vendored payload'
  check "X5 a workflow row with no vendored payload refuses, naming the fix (never a download)" "$([ "$RC" -eq 2 ] && echo 0 || echo 1)"
fi

# ---- X6: init ------------------------------------------------------------------
BRIEF=$(HOME="$HOMEDIR" bash "$SRC/bin/goblin-init" 2>&1)
printf '%s' "$BRIEF" | grep -qF 'catalogue_suggestions'
check "X6 the bare brief carries the catalogue_suggestions section" "$?"
printf '%s' "$BRIEF" | grep -qF 'discover_extras'
check "X6 the bare brief carries the discover_extras section (F7)" "$?"
printf '%s' "$BRIEF" | grep -qF 'source_url' && printf '%s' "$BRIEF" | grep -qF 'suggested_kind'
check "X6 the discover_extras proposal schema keys are named" "$?"
printf '%s' "$BRIEF" | grep -qF 'NOTHING installs at init'
check "X6 the brief states the inert rule (nothing auto-installs)" "$?"
printf '%s' "$BRIEF" | grep -qF 'allowlist'
check "X6 the brief states the allowlist rule" "$?"
# the heuristic fallback suggests from matches
P2="$WORK/repo2"; mkdir -p "$P2"; cd "$P2" || exit 1
printf '{"name":"x","dependencies":{"react":"18.0.0"},"devDependencies":{"@playwright/test":"1.0.0"}}\n' > package.json
OUT=$(HOME="$HOMEDIR" bash "$SRC/bin/goblin-init" --heuristic 2>&1)
printf '%s' "$OUT" | grep -qE '\[x\] taste-skill'
check "X6 the heuristic fallback pre-ticks a RECOMMEND row whose matches hits the repo" "$?"
printf '%s' "$OUT" | grep -qE '\[ \] currents-playwright-best-practices'
check "X6 a MAYBE row is suggested unticked (visible, never a default)" "$?"
printf '%s' "$OUT" | grep -qF 'superdesign-skill' && printf '%s' "$OUT" | grep -qF 'nuxt-skills'
RC=0
printf '%s' "$OUT" | grep -qE '\[x\] nuxt-skills' && RC=1
printf '%s' "$OUT" | grep -qE '\[ \] nuxt-skills' && RC=1
check "X6 a SKIP row is never suggested" "$([ "$RC" -eq 0 ] && echo 0 || echo 1)"
printf '%s' "$OUT" | grep -qF 'install later with: gob extras install'
check "X6 the fallback names the separate install step (init installs nothing)" "$?"
# --write honours ticks and only ticks
mkdir -p tests
printf '#!/usr/bin/env bash\nexit 0\n' > tests/run-tests.sh
chmod +x tests/run-tests.sh
git config user.name "Test Runner"; git config user.email runner@example.com
cat > proposal.md <<'EOF'
<!-- gob:begin (gobstack config — edit in place; the parser reads only this block) -->
class: software
branch: main
owner_email: runner@example.com
gate_check_cmd: bash tests/run-tests.sh
<!-- gob:end -->

## gob init summary

- a react repo

catalogue_suggestions:
  - [x] taste-skill  # react repo, RECOMMEND
  - [ ] superdesign-skill  # MAYBE, not chosen

discover_extras:
  - id: probe-discovery
    source_url: https://example.com/probe
    license: MIT
    rationale: inert probe row
    suggested_kind: skill
EOF
git add -A && git commit -q -m "seed"
OUT=$(HOME="$HOMEDIR" bash "$SRC/bin/goblin-init" --write proposal.md --yes 2>&1); RC=$?
check "X6 --write with a ticked catalogue row exits 0" "$RC"
[ -f ".gob/extras/taste/SKILL.md" ]
check "X6 --write installed the TICKED row" "$?"
[ ! -d ".gob/extras/superdesign" ] && [ ! -f ".gob/extras/superdesign-skill/SKILL.md" ]
check "X6 --write did NOT install the unticked MAYBE row" "$?"
# an unknown ticked id fails the whole write
cat > proposal2.md <<'EOF'
<!-- gob:begin (gobstack config — edit in place; the parser reads only this block) -->
class: software
branch: main
owner_email: runner@example.com
gate_check_cmd: bash tests/run-tests.sh
<!-- gob:end -->

## gob init summary

catalogue_suggestions:
  - [x] not-in-the-catalogue  # must refuse
EOF
P3="$WORK/repo3"; mkdir -p "$P3/tests"; cd "$P3" || exit 1
printf '#!/usr/bin/env bash\nexit 0\n' > tests/run-tests.sh; chmod +x tests/run-tests.sh
git init -q -b main; git config user.name "Test Runner"; git config user.email runner@example.com
git add -A && git commit -q -m "seed"
OUT=$(HOME="$HOMEDIR" bash "$SRC/bin/goblin-init" --write "$WORK/repo2/proposal2.md" --target . --yes 2>&1); RC=$?
check "X6 --write with an unknown ticked id fails (exit 2, the allowlist holds at init too)" "$([ "$RC" -eq 2 ] && echo 0 || echo 1)"

# ---- X7: the docs --------------------------------------------------------------
norm_text() { sed 's/[*_`]/ /g' "$1" | tr -s '[:space:]' ' ' | tr 'A-Z' 'a-z'; }
norm_text "$SRC/README.md" | grep -q 'the catalogue is the allowlist'
check "X7 README states the allowlist rule" "$?"
norm_text "$SRC/README.md" | grep -q 'gob extras'
check "X7 README carries the extras section" "$?"
norm_text "$SRC/README.md" | grep -q 'installs are offline by contract'
check "X7 README states the offline payload contract" "$?"
norm_text "$SRC/README.md" | grep -q 'suggests; it never installs'
check "X7 README states init-suggests-never-installs" "$?"
norm_text "$SRC/README.md" | grep -q 'the discover extras tier is proposals only'
check "X7 README documents the discover_extras tier" "$?"
norm_text "$SRC/README.md" | grep -q 'by pr or direct edit'
check "X7 README documents the curation surface (a row = PR or edit)" "$?"
norm_text "$SRC/docs/GUIDE.md" | grep -q 'the extras catalogue'
check "X7 GUIDE teaches the catalogue where a reader decides" "$?"
norm_text "$SRC/docs/GUIDE.md" | grep -q 'init suggests, the catalogue allows, you install'
check "X7 GUIDE states the one rule to hold onto" "$?"
# the dispatcher/shim name the verb (captured, not piped: the shim exits 2 and under
# pipefail grep -q's early exit SIGPIPE-races it — the same trap cmd_list documents)
SHIM_USAGE=$(node "$SRC/bin/goblin.js" 2>&1)
printf '%s' "$SHIM_USAGE" | grep -q 'gob extras'
check "X7 the shim's usage lists gob extras" "$?"
bash "$SRC/bin/goblin" --help 2>&1 | grep -qF 'gob extras'
check "X7 the dispatcher's usage lists gob extras" "$?"

# cleanup
rm -rf "$WORK" /tmp/x1.hdrs /tmp/x1.want
if [ "$fail" -eq 0 ]; then
  printf 't-extras: ALL-OK\n'
else
  printf 't-extras: FAIL\n'
fi
exit "$fail"
