#!/usr/bin/env bash
# t-mcp.sh — `gob mcp`: the MCP stdio server over the vendored harness.
#
#   M1  the handshake: initialize echoes the client protocolVersion and answers with
#       serverInfo (name gob, the VERSION source) + capabilities.tools; ping answers {}
#   M2  tools/list returns exactly the three tools with semantic-trigger descriptions
#   M3  tools/call gob_verify on a GREEN fixture: the verdict line is PASS with the
#       passed/failed counts and every FAIL row (there are none) would carry a remedy
#   M4  tools/call gob_verify on a RED fixture: verdict FAIL, the row id is named and
#       the manifest remedy cell rides under it; an unknown --only id still exits the
#       verifier's own way and the tool says so (isError), never crashes
#   M5  tools/call gob_map_status: an undeclared map says so; a declared map reports
#       each feature, its verified: date, and resolution per entry path (resolves under
#       a real token, DOES-NOT under a dead one — the FM-02 read-only half)
#   M6  tools/call gob_init_status: the gob block, gates and engine version
#   M7  protocol errors: a parse error is -32700 with id null, an unknown method is
#       -32601, an unknown tool is an isError RESULT, a notification is never answered
#   M8  init --write registers the gob MCP server: it writes the generated .mcp.json
#       exactly once; a second run states the no-op; a customized file is KEPT, never
#       overwritten; the uninstall removes the generated bytes and KEEPS a customized one
#   M9  no network, no stray spawns: the server is exercised with an empty PATH root
#       (nothing but node and the verify subprocess can run) and asserts it never
#       spawns anything but bash->goblin-verify; PT-04 over the source tree keeps the
#       file free of any endpoint, address or fetch surface
#
# The client: a real JSON-RPC driver (tests/mcp-client.py, python3 stdlib) that speaks
# the wire — write line, read line, parse — not a grep over canned bytes.
#
# Everything runs in a mktemp sandbox with HOME pointed inside it; no test writes the
# real $HOME. Run by tests/run-tests.sh.
set -uo pipefail

SRC=$(cd "$(dirname "${BASH_SOURCE[0]}")/.."/ && pwd)
SRC=${SRC%/}
WORK=$(mktemp -d)
FAILFILE="$WORK/fails"; : > "$FAILFILE"
note() { printf '      %s\n' "$*"; }
check() {
  if [ "$2" -eq 0 ]; then note "ok   $1"; else note "FAIL $1"; printf '%s\n' "$1" >> "$FAILFILE"; fi
}
trap 'rm -rf "$WORK"' EXIT

CLIENT="python3 $SRC/tests/mcp-client.py"
MCP="$SRC/bin/goblin-mcp.js"

# send <json>... — the client pipes the lines, reads until each id is answered, prints
# one response per line. A notification (no id) draws no answer by protocol.
mcp() { # <server-cmd...> -- <request json> [more...]
  local srv="$1"; shift; [ "$1" = "--" ] && shift
  printf '%s\n' "$@" | $CLIENT "$srv"
}

# ---- the fixtures --------------------------------------------------------------
# models + practice: the installer's two machine inputs
printf 'the referenced standard\n' > "$WORK/standard.md"

new_fixture() { # <tag> — a seeded, installed, committed repo
  local tag="$1"
  R="$WORK/$tag"
  mkdir -p "$R"
  ( cd "$R" && git init -q -b main && git config user.name "Test Runner" \
      && git config user.email "runner@example.com" \
      && printf '# %s\n' "$tag" > README.md \
      && git add -A && git commit -q -m "chore: seed" )
  ( cd "$R" && bash "$SRC/bin/goblin-install" --target "$R" \
      --practice "$WORK/standard.md" >/dev/null 2>&1 )
  ( cd "$R" && git add -A && git commit -q -m "chore: install gobstack" )
  # the HANDOFF placeholder red is the one expected red; name a real HEAD to go green
  ( cd "$R" && HEAD_NOW=$(git rev-parse --short HEAD) \
      && sed -i "s/^- HEAD when this file was written: .*/- HEAD when this file was written: \`$HEAD_NOW\`/" HANDOFF.md \
      && git add -A && git commit -q -m "docs: HANDOFF names the HEAD it describes" )
}

# write_proposal <dir> — the minimal proposal `gob init --write` accepts (one gate, one
# feature whose entry path is the committed README). The same file M8 and M10 drive.
write_proposal() {
  local dir="$1" pro="$1/.gob-init-proposal.md"
  {
    printf '<!-- gob:begin (gobstack config — edit in place; the parser reads only this block) -->\n'
    printf 'gate_commit_cmd: true\nfeature_map: features/README.md\n'
    printf '<!-- gob:end -->\n'
    printf '\n## gob init summary\n\n- fixture\n\n## feature-map\n\n'
    printf '### features/README.md\n\n```md\n# Features\n\n- [readme](./readme.md) — the repo readme\n```\n\n'
    printf '### features/readme.md\n\n```md\n---\nfeature: readme\nentry_paths:\n  - README.md\nverified: never-driven (2024-01-01)\n---\n'
    printf '# readme\n\nx\n\n## Sub-features\n\n- x\n\n## How to get to it (user POV)\n\n- x\n\n## Driving it with bash\n\nRun `cat README.md`.\n\n## Gotchas\n\n- x\n```\n'
  } > "$pro"
  printf '%s\n' "$pro"
}

# ---- M1: the handshake ---------------------------------------------------------
OUT=$(cd "$WORK" && printf '%s\n%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"t-mcp","version":"0"}}}' \
  '{"jsonrpc":"2.0","method":"notifications/initialized"}' \
  '{"jsonrpc":"2.0","id":2,"method":"ping"}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
check "M1 the client got answers for both requests" "$([ "$(printf '%s\n' "$OUT" | grep -c '^{"jsonrpc"')" = "2" ] && echo 0 || echo 1)"
printf '%s' "$OUT" | grep -q '"id":1'
check "M1 initialize is answered under its own id" "$?"
printf '%s' "$OUT" | grep -q '"protocolVersion":"2025-06-18"'
check "M1 the server echoes the client protocolVersion" "$?"
printf '%s' "$OUT" | grep -q '"serverInfo":{"name":"gob"'
check "M1 serverInfo names the server gob" "$?"
printf '%s' "$OUT" | grep -q "\"version\":\"$(cat "$SRC/VERSION")\""
check "M1 serverInfo carries the VERSION source, not a copy" "$?"
printf '%s' "$OUT" | grep -q '"capabilities":{"tools"'
check "M1 capabilities declare tools" "$?"
printf '%s' "$OUT" | grep -q '"id":2,"result":{}'
check "M1 ping answers {}" "$?"

# ---- M1b: the initialized notification draws NO answer -------------------------
OUTN=$(printf '%s\n' '{"jsonrpc":"2.0","method":"notifications/initialized"}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
[ -z "$OUTN" ]
check "M1b the initialized notification draws NO answer" "$?"

# ---- M2: tools/list ------------------------------------------------------------
OUT=$(printf '%s\n' '{"jsonrpc":"2.0","id":7,"method":"tools/list"}' | python3 "$SRC/tests/mcp-client.py" "node $MCP")
for tool in gob_verify gob_map_status gob_init_status; do
  printf '%s' "$OUT" | grep -q "\"name\":\"$tool\""
  check "M2 tools/list carries $tool" "$?"
done
printf '%s' "$OUT" | grep -q 'Call this BEFORE reporting any coding task complete'
check "M2 gob_verify's description is the semantic trigger" "$?"
printf '%s' "$OUT" | grep -q 'inputSchema'
check "M2 every tool carries an inputSchema" "$?"

# ---- M3: gob_verify on a GREEN fixture -----------------------------------------
new_fixture green
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'gate: PASS'
check "M3 the green fixture verifies PASS through the tool" "$?"
printf '%s' "$OUT" | grep -qE 'gate: PASS — [0-9]+ passed, 0 failed'
check "M3 the verdict line carries the passed/failed counts" "$?"
printf '%s' "$OUT" | grep -q 'PASS  IN-01'
check "M3 the row lines keep the id + status shape" "$?"

# ---- M4: gob_verify on a RED fixture -------------------------------------------
new_fixture red
mkdir -p "$R/src" && printf 'export const a: any = 1;\n' > "$R/src/red.ts"   # a BN-01 violation: a deterministic red with a remedy
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'gate: FAIL'
check "M4 the red fixture verifies FAIL through the tool" "$?"
printf '%s' "$OUT" | grep -q 'gate: FAIL — [0-9]*[0-9] passed, [1-9][0-9]* failed'
check "M4 the verdict line names the failed count" "$?"
printf '%s' "$OUT" | grep -q 'remedy: '
check "M4 every FAIL row carries its remedy line" "$?"
# --only selection passes through
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{"only":"IN-01"}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'IN-01'
check "M4 the only: argument reaches the verifier" "$?"
# a repo with no install: isError, never a crash
OUT=$(cd "$WORK" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q '"isError":true'
check "M4 a repo with no engine is an isError result, not a crash" "$?"
printf '%s' "$OUT" | grep -q 'gobstack init'
check "M4 and the error names the first step" "$?"

# ---- M4b: gob_verify honours `target` (QA fix v2-qa issue 7) --------------------
# The QA sim called gob_verify with a bogus target from an installed cwd and got the
# CWD's matrix back — an agent could report the wrong repo as verified. Three pins:
# the resolved path is echoed, a real second fixture verifies by target, and a target
# that is not a gobstack repo is a refusal naming the resolved path.
new_fixture green
GREEN_R="$R"
new_fixture red
mkdir -p "$R/src" && printf 'export const a: any = 1;\n' > "$R/src/red.ts"   # a BN-01 violation: a deterministic red with a remedy
# run from the RED fixture, verify the GREEN fixture by target: the verdict must be the
# TARGET's, not the cwd's
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  "{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/call\",\"params\":{\"name\":\"gob_verify\",\"arguments\":{\"target\":\"$GREEN_R\"}}}" \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q "verified: $GREEN_R"
check "M4b the result echoes the resolved verified path" "$?"
printf '%s' "$OUT" | grep -q 'gate: PASS'
check "M4b target=green-fixture verifies the TARGET, not the cwd" "$?"
# a bogus target is a refusal, never a silent fall-back to the cwd's matrix
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{"target":"/nonexistent-qa-target"}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q '"isError":true'
check "M4b a bogus target is an isError refusal" "$?"
printf '%s' "$OUT" | grep -q 'target is not a directory: /nonexistent-qa-target'
check "M4b the refusal names the exact resolved path" "$?"
printf '%s' "$OUT" | grep -q 'gate:'
[ $? -eq 1 ]; check "M4b a refused target never returns the cwd's matrix" "$?"
# an existing but non-gobstack directory is refused the same way
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{"target":"'"$WORK"'"}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'target is not a gobstack repo'
check "M4b a non-gobstack dir is refused by name (no .gob engine, no gob block)" "$?"

# ---- M5: gob_map_status --------------------------------------------------------
new_fixture maps
# an undeclared map: the SKIP-with-reason shape
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_map_status","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'feature_map: is empty'
check "M5 an undeclared map is the empty state, not an error" "$?"
# declare a map with one real feature (entry path resolves) and one dead one
mkdir -p "$R/features"
printf 'export function checkout() { return 1 }\n' > "$R/src-cart.js"
cat > "$R/features/checkout.md" <<'EOF'
---
feature: checkout
verified: 2026-10-01
entry_paths:
  - export function checkout
---
## Sub-features
cart math
## How to get to it (user POV)
buy something
## Driving it with curl
call the export
## Gotchas
none yet
EOF
cat > "$R/features/legacy.md" <<'EOF'
---
feature: legacy
verified: never-driven (generated 2026-10-01)
entry_paths:
  - export function deleted_in_2025
---
## Sub-features
old path
## How to get to it (user POV)
n/a
## Driving it with curl
n/a
## Gotchas
it is gone
EOF
printf '# features\n\n- [checkout](./checkout.md) - cart math\n- [legacy](./legacy.md) - old path\n' > "$R/features/README.md"
# feature_map: into the gob block (the declared key the verifier reads)
sed -i 's/^practice_sha256:/feature_map: features\/README.md\npractice_sha256:/' "$R/AGENTS.md"
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_map_status","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'map: features/README.md (2 feature file(s))'
check "M5 the declared map is read with its feature count" "$?"
printf '%s' "$OUT" | grep -q 'checkout.md  verified: 2026-10-01'
check "M5 each feature carries its verified: date" "$?"
printf '%s' "$OUT" | grep -q 'export function checkout -> resolves'
check "M5 a live entry path is reported as resolving" "$?"
printf '%s' "$OUT" | grep -q 'export function deleted_in_2025 -> DOES NOT occur in source'
check "M5 a dead entry path is reported as FM-02 would FAIL" "$?"
printf '%s' "$OUT" | grep -q 'freshness clause'
check "M5 the tool states the freshness clause stays with goblin-verify" "$?"

# ---- M6: gob_init_status -------------------------------------------------------
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_init_status","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'gob block: present'
check "M6 the tool reports the gob block" "$?"
printf '%s' "$OUT" | grep -q 'gate_commit_cmd: '
check "M6 the declared gates are named" "$?"
printf '%s' "$OUT" | grep -q "engine version: $(cat "$SRC/VERSION")"
check "M6 the engine version comes from the vendored source" "$?"
OUT=$(cd "$WORK" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_init_status","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q '"isError":true'
check "M6 a repo with no gob block is an isError result" "$?"

# ---- M7: protocol errors -------------------------------------------------------
# The parse-error answer is id:null, which no request is waiting on — pair it with a
# ping so the client stays open long enough to carry the line out.
OUT=$(printf 'not json at all\n%s\n' '{"jsonrpc":"2.0","id":9,"method":"ping"}' | python3 "$SRC/tests/mcp-client.py" "node $MCP" 2>&1)
printf '%s' "$OUT" | grep -q '"id":null,"error":{"code":-32700'
check "M7 an unparseable line is -32700 with id null" "$?"
OUT=$(printf '%s\n' '{"jsonrpc":"2.0","id":9,"method":"resources/list"}' | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q '"id":9,"error":{"code":-32601'
check "M7 an unknown method is -32601" "$?"
OUT=$(printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"not_a_tool","arguments":{}}}' \
  | python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q '"isError":true'
check "M7 an unknown tool is an isError RESULT (never a crash)" "$?"
printf '%s' "$OUT" | grep -q 'unknown tool: not_a_tool'
check "M7 and the result names the tool it refused" "$?"

# ---- M8: init --write --with-mcp-config registers MCP + the uninstall clause ------
# v3 enhance layer: the registration is OPT-IN — the named removal that pays for hooks
# emission. M8 drives the writer with the flag and pins ask-once in both directions.
new_fixture mcpcfg
GEN='{"mcpServers":{"gob":{"command":"npx","args":["-y","@techgoblin/gobstack","mcp"]}}}'
PRO=$(write_proposal "$R")
OUT=$(cd "$R" && bash "$SRC/bin/goblin-init" --write "$PRO" --yes --with-mcp-config 2>&1); RC=$?
check "M8 init --write --with-mcp-config exits 0" "$([ "$RC" -eq 0 ] && echo 0 || echo 1)"
[ -f "$R/.mcp.json" ] && [ "$(cat "$R/.mcp.json")" = "$GEN" ]
check "M8 --with-mcp-config writes .mcp.json naming the gob server (the generated bytes)" "$?"
printf '%s' "$OUT" | grep -q 'wrote .*/\.mcp\.json'
check "M8 and the run says it wrote the registration" "$?"
OUT=$(cd "$R" && bash "$SRC/bin/goblin-init" --write "$PRO" --yes --with-mcp-config 2>&1); RC=$?
check "M8 a second identical --write exits 0 (ask-once: a no-op, not an overwrite)" "$([ "$RC" -eq 0 ] && echo 0 || echo 1)"
printf '%s' "$OUT" | grep -q 'already carries the generated registration'
check "M8 and names the no-op" "$?"
printf '{"mcpServers":{"gob":{"command":"node","args":["/team/own/gob.js"]}}}\n' > "$R/.mcp.json"
OUT=$(cd "$R" && bash "$SRC/bin/goblin-init" --write "$PRO" --yes --with-mcp-config 2>&1); RC=$?
check "M8 a customized .mcp.json does not fail the install (exit 0)" "$([ "$RC" -eq 0 ] && echo 0 || echo 1)"
printf '%s' "$OUT" | grep -qF 'kept '
check "M8 and the run says the customized registration is kept" "$?"
[ "$(cat "$R/.mcp.json")" = '{"mcpServers":{"gob":{"command":"node","args":["/team/own/gob.js"]}}}' ]
check "M8 the customized file is untouched (never overwritten)" "$?"

# A customized registration survives the uninstall — on a FRESH fixture: the uninstall
# consumes the install record, so each uninstall clause needs its own install.
new_fixture mcpkeep
printf '{"mcpServers":{"gob":{"command":"node","args":["/team/own/gob.js"]}}}\n' > "$R/.mcp.json"
OUT=$(bash "$SRC/bin/goblin-install" --target "$R" --uninstall 2>&1)
printf '%s' "$OUT" | grep -q 'kept .mcp.json'
check "M8 the uninstall KEEPS a customized registration" "$?"
[ -f "$R/.mcp.json" ]
check "M8 and the customized file is still there" "$?"

new_fixture mcprm
printf '%s\n' "$GEN" > "$R/.mcp.json"
OUT=$(bash "$SRC/bin/goblin-install" --target "$R" --uninstall 2>&1); RC=$?
note "$(printf '%s' "$OUT" | grep -iE 'mcp' || echo 'no .mcp line')"
check "M8 the uninstall of a generated registration exits 0" "$([ "$RC" -eq 0 ] && echo 0 || echo 1)"
[ ! -e "$R/.mcp.json" ]
check "M8 and the generated bytes are removed" "$?"

# ---- M9: local-only (no network, no stray spawns) -------------------------------
# The strongest available form of 'network disabled': run a full green verify with PATH
# reduced to the shell's own tools plus node, in a sandbox where nothing else exists —
# there is nothing to reach out with. The tool must still answer. (The fixture is fresh:
# the uninstall clauses above consumed their installs' records.)
new_fixture hermetic
SB="$WORK/hermetic-sb"; mkdir -p "$SB/bin"
for b in node python3 bash git awk sed grep cut ls sha256sum shasum cat dirname basename date head sort tr wc mktemp env pwd test command sleep; do
  p=$(command -v "$b" 2>/dev/null) && [ -e "$SB/bin/$b" ] || ln -s "$p" "$SB/bin/$b" 2>/dev/null
done
OUT=$(cd "$R" && printf '%s\n%s\n' \
  '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2024-11-05"}}' \
  '{"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":"gob_verify","arguments":{}}}' \
  | env PATH="$SB/bin" HOME="$WORK" python3 "$SRC/tests/mcp-client.py" "node $MCP")
printf '%s' "$OUT" | grep -q 'gate: PASS'
check "M9 the server answers a full verify with nothing but the shell's own tools on PATH" "$?"
# the source tree carries no endpoint surface (PT-04's body, scoped to the new file)
ENDPOINTS=$(grep -nE 'https?://[^ ]*[^ )>`]|[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|net\.connect|dgram|dns\.|tls\.|fetch\(' "$MCP" | grep -v 'npx -y @techgoblin/gobstack' || true)
[ -z "$ENDPOINTS" ]
check "M9 no endpoint, address or socket surface in the server source" "$?"
# the mcp verb is exercised through the npm shim (the one dispatcher)
OUT=$(printf '%s\n' '{"jsonrpc":"2.0","id":1,"method":"ping"}' | python3 "$SRC/tests/mcp-client.py" "node $SRC/bin/goblin.js mcp")
printf '%s' "$OUT" | grep -q '"id":1,"result":{}'
check "M9 the npm shim routes mcp under node (SH-M1: bash choked on the .js target)" "$?"

# ---- v3: registration is opt-in, and the surface says so ------------------------
# The default --write writes NO .mcp.json (the named removal); the flag is named on the
# brief and the done screen so the opt-in is discoverable, and the default install carries
# no registration a repo never asked for.
new_fixture coach
OUT=$(cd "$R" && bash "$SRC/bin/goblin-init" 2>&1)
printf '%s' "$OUT" | grep -q 'gob init --write'
check "M10 the bare init brief still names the writer" "$?"
printf '%s' "$OUT" | grep -q -- '--with-mcp-config'
check "M10 the brief names the --with-mcp-config opt-in" "$?"
PRO=$(write_proposal "$R")
OUT=$(cd "$R" && bash "$SRC/bin/goblin-init" --write "$PRO" --yes 2>&1)
printf '%s' "$OUT" | grep -q 'next:'
check "M10 the --write done screen prints its next steps" "$?"
[ ! -e "$R/.mcp.json" ]
check "M10 the default --write writes NO .mcp.json (opt-in means opt-in)" "$?"
OUT=$(cd "$R" && bash "$SRC/bin/goblin-init" --write "$PRO" --yes --with-mcp-config 2>&1)
[ -f "$R/.mcp.json" ]
check "M10 the flag registers MCP itself (.mcp.json on disk)" "$?"

FAIL_N=$(wc -l < "$FAILFILE" | tr -d ' ')
if [ "${FAIL_N:-0}" -eq 0 ]; then
  printf '      t-mcp: ALL-OK\n'
  exit 0
fi
printf '      t-mcp: FAILED (%s)\n' "$FAIL_N"
exit 1
